### ISSUE TITLE
mode melting_temperature with custom lattice

### ISSUE THREAD

**Issue by Leimeroth** [ICAMS/calphy#33]
When specifying a file instead of a predefined lattice melting_temperature calculations fail with:

ValueError("Unknown lattice found. Allowed options are BCC, FCC, HCP, DIA, SC or LQD; or an input file.")

Trying to find the reason for the problem I edited 

raise ValueError("Unknown lattice found. Allowed options are BCC, FCC, HCP, DIA, SC or LQD; or an input file.")
to 
raise ValueError(f"Unknown lattice {calc.lattice} found. Allowed options are BCC, FCC, HCP, DIA, SC or LQD; or an input file.")

This prints 
Unknown lattice ORC found.
which didn't really help me because I could not find out where my conf.data was transformed to ORC tbh.

My input file looks like this. I tried with a relative and an absolute path for the lattice, but this didn't change anything.
```
calculations:
- lattice: /nfshome/leimeroth/pyiron/projects/CalculationsForJochen/Calphy/Ga/TestPotentials/2003--Nord-J--Ga-N--LAMMPS--ipr1/melting_point/conf.data
  mode: melting_temperature
  nsims: 1
  pressure:
  - 0
element:
- Ga
mass:
- 69.723
md:
  dtemp: 100
  nsmall: 10000
  pair_coeff: '* * 2003_GaN.tersoff Ga N'
  pair_style: tersoff
  pdamp: 0.1
  tdamp: 0.1
  te: 10000
  tguess: 400
  timestep: 0.001
  ts: 15000
queue:
  cores: 1
  scheduler: local

```
