### ISSUE TITLE
pair_coeff for deepmd potential

### ISSUE THREAD

**Issue by gswylq** [ICAMS/calphy#90]
Hello every,

I have successfully installed calphy-1.2.13,   The test result of Example 02 are consistent with the results of the tutorial using the eam potential. When I use the deepmd potential to calculated the phase transition, an error occurs. 
It is normal when calculated using lammps (with deepmd potential) alone, and the input is added to attachment.

I hope you can give me some advice. Thank you.

Q. Li

The error is that (ERROR: pair_coeff: element /home/gswylq/soft_calphy/calphy/examples/AgAu/Li not found in the model (/home/conda/feedstock_root/build_artifacts/libdeepmd_1693540729941/work/source/lmp/pair_deepmd.cpp:1161)
Last command: pair_coeff * * /home/gswylq/soft_calphy/calphy/examples/AgAu/Li Si)

The deepmd potential is from the website (https://www.aissquare.com/models/detail?pageType=models&name=AgAu-nanoalloy-model)

[AgAu.zip](https://github.com/ICAMS/calphy/files/13108108/AgAu.zip)

**Comment by srmnitc** [comment]
Looking at the input file, I can see the probable issue:

```
calculations:
- element:
  - Ag
  - Au
  lattice: AgAu_BCC.data
  mass:
  - 6.941
  - 28.08
  md:
    barostat_damping: 0.1
    equilibration_control: nose_hoover
    thermostat_damping: 0.1
    timestep: 0.002
  mode: ts
  n_equilibration_steps: 10000
  n_iterations: 1
  n_switching_steps: 25000
  pair_coeff: '* * Li Si'
  pair_style: deepmd  ../LiSi.pb
  ```

The pair coeff asks for elements Li and Si, whereas the `element` keyword mentions Ag and Au. In you update the input file to:

```
calculations:
- element:
  - Li
  - Si
  lattice: AgAu_BCC.data
  mass:
  - 6.941
  - 28.08
  md:
    barostat_damping: 0.1
    equilibration_control: nose_hoover
    thermostat_damping: 0.1
    timestep: 0.002
  mode: ts
  n_equilibration_steps: 10000
  n_iterations: 1
  n_switching_steps: 25000
  pair_coeff: '* * Li Si'
  pair_style: deepmd  ../LiSi.pb
  ```
  
  Should work. The rest of the input file also needs to be updated. The lattice also seems to take an AgAu structure as input. That should also be changed.
